### ISSUE TITLE
Capitalized package name does not work (Linux)

### ISSUE THREAD

**Issue by Cyrille37** [abenevaut/laravel-opcache-clear#1]
Hello,
I cannot make you package works on Linux & Php7.1.
Here is the error :
```
 [Symfony\Component\Debug\Exception\FatalThrowableError]                              
  Class 'ABENEVAUT\Opcache\Clear\App\Providers\OpcacheClearServiceProvider' not found  
 ```
Perhaps it's because of the all capital letters in package name ?

**Comment by Cyrille37** [comment]
My report is not good.
It works if requiring the package in composer.json application, but not in a sub-module.
I'll investigate later.
Cheers.

**Comment by abenevaut** [comment]
Composer is the way to works with! The namespaces are loaded from composer autoload and psr rules associated.

**Comment by abenevaut** [comment]
And... with laravel...
